# Generated by Django 3.2.4 on 2021-06-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_favorite_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom_categorie',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='marque',
            old_name='nom_marque',
            new_name='nom',
        ),
    ]
