# Generated by Django 3.2.4 on 2021-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210621_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='nom_site',
            field=models.ImageField(upload_to=''),
        ),
    ]
