# Generated by Django 3.2.4 on 2021-06-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_website_nom_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_next',
            field=models.ImageField(default=1, upload_to='image_articles'),
            preserve_default=False,
        ),
    ]
