# Generated by Django 3.2.4 on 2021-06-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_cart_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='image_articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_next',
            field=models.FileField(upload_to='image_articles'),
        ),
    ]
