# Generated by Django 3.2.4 on 2021-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210624_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='code_postal',
        ),
        migrations.AddField(
            model_name='checkout',
            name='zip_code',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
