# Generated by Django 3.2.4 on 2021-06-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210625_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='company_name',
            field=models.TextField(),
        ),
    ]
