# Generated by Django 3.2.4 on 2021-10-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_checkout_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('prix', models.BooleanField()),
                ('quantity', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_article', to='website.article')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_checkout', to='website.checkout')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItem',
            },
        ),
    ]
