# Generated by Django 3.2.4 on 2021-10-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20211027_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='prix',
            field=models.FloatField(),
        ),
    ]
