# Generated by Django 3.2.4 on 2021-11-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20211103_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
